[env:sbse]
extends = base_esp32

lib_deps = ${base_esp32.lib_deps}
           https://github.com/Tinkerforge/tfnetwork#9121acc27afbdd51da50a29e635334d8e14e99da
           https://github.com/Tinkerforge/WireGuard-ESP32-Arduino#161e3c94

build_flags = ${base_esp32.build_flags}
              -DTF_LOCAL_ENABLE=1
              -DTF_NET_MAX_CLIENT_COUNT=10

custom_product_id = sbse
custom_branding = TF

custom_options = ${base_esp32.custom_options}
                 product_name = "SBSE Controller"
                 config_type = "brick"
                 hostname_prefix = "sbse"
                 firmware_update_latest_url = ""
                 manual_url = ""

custom_backend_modules = ESP32 Brick
                         Watchdog
                         Uptime Tracker
                         Network
                         NTP
                         Wifi
                         Network Helper
                         Http
                         WS
                         Event
                         System
                         Firmware Update
                         Authentication
                         Device Name
                         Coredump
                         Pwa
                         Certs
                         Network Lib
                         Modbus TCP Client
                         Sbse Controller

custom_frontend_modules = Device Name
                          Network
                          Wifi
                          Certs
                          NTP
                          Rtc
                          Time
                          Authentication
                          Event Log
                          System
                          Firmware Update
                          Status Alerts
                          Network Group
                          System Group

custom_frontend_components = Network Group $ Open
                               Network
                               Wifi | Wifi STA
                               Wifi | Wifi AP
                             Network Group $ Close
                             System Group $ Open
                               System
                               Certs
                               Time
                               Authentication
                               Event Log
                               Firmware Update
                             System Group $ Close

custom_frontend_status_components = Device Name
                                    Status Alerts
                                    Wifi
                                    Time

; ============================================================================

[env:sbse_debug]
extends = env:sbse

custom_frontend_debug = true

; ============================================================================

[env:sbse_web]
extends = env:sbse

custom_web_only = true

; ============================================================================

[env:sbse_web_debug]
extends = env:sbse

custom_web_only = true
custom_frontend_debug = true
